// Generated by https://LastFM.ReaderCore.io

namespace LastFM.ReaderCore
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class CleaningRule
    {
        [JsonProperty("rules")]
        public Rules Rules { get; set; }
    }

    public partial class Rules
    {
        [JsonProperty("rule")]
        public Rule[] Rule { get; set; }
    }

    public partial class Rule
    {
        [JsonProperty("sequence")]
        public long Sequence { get; set; }

        [JsonProperty("oldValue")]
        public string OldValue { get; set; }

        [JsonProperty("isRegEx")]
        public bool IsRegEx { get; set; }

        [JsonProperty("newValue", NullValueHandling = NullValueHandling.Ignore)]
        public string NewValue { get; set; }
    }

    public partial class CleaningRule
    {
        public static CleaningRule FromJson(string json) => JsonConvert.DeserializeObject<CleaningRule>(json, LastFM.ReaderCore.Converter.Settings);
    }
}
