name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Push docker
      uses: manusa/actions-publish-docker@v1.0.1
      with:
        # Name of the Docker image
        name: lastfmreader
        # Tag for the Docker image
        tag: latest
        # Username for Docker registry
        username: wesback
        # Password for Docker registry
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        # Registry URL
